### PR TITLE
Upload missing diagram files for doc

### PR DESCRIPTION
**Pull request by monaiuu**
## Summary of changes

_Provide a detailed description of proposed changes._

-

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `Overview`
- [ ] `Anchor System`
- [ ] `dApps`
- [ ] `Tangle`
- [ ] `Protocols`
- [ ] `Relayers`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. Closes #233)._

- Closes https://github.com/webb-tools/tangle-docs/issues/55

---

### Code Checklist

- [ ] I have tested that prove my changes are working as intended
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by AtelyPham — COMMENTED** [review]
The diagrams still seem to be loading issues. Please check the following sections:

- https://deploy-preview-57--tangle-docs.netlify.app/developers/services#multi-party-computation-mpc
- https://deploy-preview-57--tangle-docs.netlify.app/developers/services#zksnarks-as-a-service-zksaas

**Comment by monaiuu** [comment]
> The diagrams still seem to be loading issues. Please check the following sections:
> 
> * https://deploy-preview-57--tangle-docs.netlify.app/developers/services#multi-party-computation-mpc
> * https://deploy-preview-57--tangle-docs.netlify.app/developers/services#zksnarks-as-a-service-zksaas

Just uploading to /image file first before I link it in Doc in separate PR

**Comment by AtelyPham** [comment]
> > The diagrams still seem to be loading issues. Please check the following sections:
> > 
> > * [deploy-preview-57--tangle-docs.netlify.app/developers/services#multi-party-computation-mpc](https://deploy-preview-57--tangle-docs.netlify.app/developers/services#multi-party-computation-mpc)
> > * [deploy-preview-57--tangle-docs.netlify.app/developers/services#zksnarks-as-a-service-zksaas](https://deploy-preview-57--tangle-docs.netlify.app/developers/services#zksnarks-as-a-service-zksaas)
> 
> Just uploading to /image file first before I link it in Doc in separate PR

Could you also address this on the same PR? It would be better since these tasks aim to resolve the same issue.

**Comment by monaiuu** [comment]
> > > The diagrams still seem to be loading issues. Please check the following sections:
> > > 
> > > * [deploy-preview-57--tangle-docs.netlify.app/developers/services#multi-party-computation-mpc](https://deploy-preview-57--tangle-docs.netlify.app/developers/services#multi-party-computation-mpc)
> > > * [deploy-preview-57--tangle-docs.netlify.app/developers/services#zksnarks-as-a-service-zksaas](https://deploy-preview-57--tangle-docs.netlify.app/developers/services#zksnarks-as-a-service-zksaas)
> > 
> > 
> > Just uploading to /image file first before I link it in Doc in separate PR
> 
> Could you also address this on the same PR? It would be better since these tasks aim to resolve the same issue.

OK lemme figure out how lol

**Review by AtelyPham — APPROVED** [review]

**Pull request merged**
